[workspace]
members = [
  "box-test",
  "color-cl",
  "color-trans",
  "expr-eval",
  "minigrep",
  "rc-test",
  "rust-wintun",
  "strings",
  "trait-test",
  "unsafe-test",
  "vector",
  "wea-tool",
]
